import molecular_biology_promoters_transcription_initiation_lemma_canonical_lane_mathlib.GateLemmas
namespace HautevilleHouse
namespace molecular_biology_promoters_transcription_initiation_lemma_canonical_lane_mathlib
structure ConstrainedTheoremClosure where
  admissible :: intro :: constraint :: consequence :: proof ::
theorem canonical : ConstrainedTheoremClosure :=
  ConstrainedTheoremClosure.intro
end molecular_biology_promoters_transcription_initiation_lemma_canonical_lane_mathlib
end HautevilleHouse
